services:
  hive-bridge:
    container_name: hive-bridge
    build:
      context: .
      network: host
    restart: unless-stopped
    init: true
    tty: true
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - ENV_VAR=production
    networks:
      - hive-bridge
networks:
  hive-bridge:
    enable_ipv6: true
